services:
  neo4j_majo:
    image: neo4j:latest
    container_name: neo4j_db
    restart: always
    environment:
      - NEO4J_AUTH=${NEO4J_USER}/${NEO4J_PASSWORD}
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data
      - ./import:/import
    networks:
      - app_network

  backend_majo:
    build: ./backend
    container_name: express_backend
    restart: always
    depends_on:
      - neo4j_majo
    env_file:
      - .env # Load all environment variables from .env file
    ports:
      - "${EXPRESS_PORT}:3000"
    networks:
      - app_network

volumes:
  neo4j_data:

networks:
  app_network:
    driver: bridge
